//
//  BCStyleKit.m
//  BeaconCam
//
//  Created by Ryan Khalili on 5/9/14.
//  Copyright (c) 2014 CompanyName. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import "BCStyleKit.h"


@implementation BCStyleKit

#pragma mark Initialization

+ (void)initialize
{
}

#pragma mark Drawing Methods

+ (void)drawModeButtonWithFrame: (CGRect)frame text: (NSString*)text highlighted: (BOOL)highlighted;
{
    //// Color Declarations
    UIColor* color = [UIColor colorWithRed: 0.636 green: 0.589 blue: 0.701 alpha: 1];
    CGFloat colorRGBA[4];
    [color getRed: &colorRGBA[0] green: &colorRGBA[1] blue: &colorRGBA[2] alpha: &colorRGBA[3]];

    UIColor* color2 = [UIColor colorWithRed: (colorRGBA[0] * 0.4 + 0.6) green: (colorRGBA[1] * 0.4 + 0.6) blue: (colorRGBA[2] * 0.4 + 0.6) alpha: (colorRGBA[3] * 0.4 + 0.6)];
    UIColor* color3 = [color colorWithAlphaComponent: 0.5];

    //// Rectangle Drawing
    CGRect rectangleRect = CGRectMake(CGRectGetMinX(frame) + 4, CGRectGetMinY(frame) + 3, CGRectGetWidth(frame) - 8, CGRectGetHeight(frame) - 8);
    UIBezierPath* rectanglePath = [UIBezierPath bezierPathWithRoundedRect: rectangleRect cornerRadius: 10];
    [color2 setFill];
    [rectanglePath fill];
    [color setStroke];
    rectanglePath.lineWidth = 3.5;
    [rectanglePath stroke];
    NSMutableParagraphStyle* rectangleStyle = NSMutableParagraphStyle.defaultParagraphStyle.mutableCopy;
    rectangleStyle.alignment = NSTextAlignmentCenter;

    NSDictionary* rectangleFontAttributes = @{NSFontAttributeName: [UIFont fontWithName: @"Avenir-Light" size: UIFont.buttonFontSize], NSForegroundColorAttributeName: UIColor.blackColor, NSParagraphStyleAttributeName: rectangleStyle};

    [text drawInRect: CGRectOffset(rectangleRect, 0, (CGRectGetHeight(rectangleRect) - [text boundingRectWithSize: rectangleRect.size options: NSStringDrawingUsesLineFragmentOrigin attributes: rectangleFontAttributes context: nil].size.height) / 2) withAttributes: rectangleFontAttributes];


    if (highlighted)
    {
        //// Rectangle 2 Drawing
        UIBezierPath* rectangle2Path = [UIBezierPath bezierPathWithRoundedRect: CGRectMake(CGRectGetMinX(frame) + 4, CGRectGetMinY(frame) + 3, CGRectGetWidth(frame) - 8, CGRectGetHeight(frame) - 8) cornerRadius: 10];
        [color3 setFill];
        [rectangle2Path fill];
        [color3 setStroke];
        rectangle2Path.lineWidth = 3.5;
        [rectangle2Path stroke];
    }
}

@end
