//
//  BCStyleKit.h
//  BeaconCam
//
//  Created by Ryan Khalili on 5/9/14.
//  Copyright (c) 2014 CompanyName. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>


@interface BCStyleKit : NSObject

// Drawing Methods
+ (void)drawModeButtonWithFrame: (CGRect)frame text: (NSString*)text highlighted: (BOOL)highlighted;

@end
