//
//  BCStyleKit.h
//  BeaconCam
//
//  Created by Ryan Khalili on 5/20/14.
//  Copyright (c) 2014 CompanyName. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>


@interface BCStyleKit : NSObject

// iOS Controls Customization Outlets
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* genericButtonTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* settingsIconTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* exitButtonTargets;

// Drawing Methods
+ (void)drawGenericButtonWithText: (NSString*)text highlighted: (BOOL)highlighted;
+ (void)drawSettingsIconWithHighlighted: (BOOL)highlighted;
+ (void)drawExitButtonWithHighlighted: (BOOL)highlighted;

// Generated Images
+ (UIImage*)imageOfGenericButtonWithText: (NSString*)text highlighted: (BOOL)highlighted;
+ (UIImage*)imageOfSettingsIconWithHighlighted: (BOOL)highlighted;
+ (UIImage*)imageOfExitButtonWithHighlighted: (BOOL)highlighted;

@end
